### ISSUE TITLE
loadRealData(np.loadtxt()) does not work

### ISSUE THREAD

**Issue by sosuts** [ismal/DL-MSS#1]
Hi!
I am trying to walk through the notebook and check how everything is working.
When I tried to load a data in MA_DataProcessing_UserFriendly_NEW.ipynb, 
```python
xfile, yfile = loadRealData(np.loadtxt(pathToFiles + name))
```
returns 
```python
could not convert string to float: 'frame,t,trajectory,x,y'
```

Passing ```delimiter=","``` argument still returns a similar error.
```python
could not convert string to float: 'frame'
```

Do you have any idea how to fix this?
Thank you in advance.

P.S. It would be great if you could upload a ```sample.csv``` to this repository!

**Comment by ismal** [comment]
Now I uploaded the example file which is called 'tracks.simple.filtered.txt'. The format is described on the website of the SOSTracking plugin http://smal.ws/wp/software/sosplugin/

<img width="747" alt="image" src="https://user-images.githubusercontent.com/345975/83555707-fcf10300-a50e-11ea-86fe-15318a8e53c0.png">

Only the first 4 columns are important/used by DL-MSS
